apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx 
  nodeSelector: 
    hardware: gcp  
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gcp"
    effect: "NoSchedule"